// Дати показано за київським часом (UTC+3 на дату публікації).
window.CYBERPW_VIDEOS = [
  {
    "id": "yNslTHLQEzg",
    "originalTitle": "Крафт сетів (Cyber.pw Асистент)",
    "title": "Сплануй цілий сет",
    "category": "craft",
    "module": "VIP-майстерня",
    "seconds": 24,
    "date": "2026-09-13",
    "description": "Почни з переліку того, що вже є і що потрібно докупити.",
    "status": "vip",
    "icon": "armor"
  },
  {
    "id": "tf3h1I3RJ1E",
    "originalTitle": "title helper  (Сyber.pw Асистент)",
    "title": "Титули без ручних координат",
    "category": "world",
    "module": "TitulHelper",
    "seconds": 38,
    "date": "2026-09-13",
    "description": "Синхронізуй прогрес і переходь до наступного етапу.",
    "status": "ready",
    "icon": "compass"
  },
  {
    "id": "75gX4-s2VjU",
    "originalTitle": "Крафт чи покупка? (Сyber.pw Асистент)",
    "title": "Крафтити чи купити?",
    "category": "craft",
    "module": "Крафт-калькулятор",
    "seconds": 35,
    "date": "2026-09-13",
    "description": "Порівняй собівартість і ціну готового предмета.",
    "status": "ready",
    "icon": "coins"
  },
  {
    "id": "x0ngM2Dsg7o",
    "originalTitle": "Макроси в різні вікна(Cyber.pw Асистент)",
    "title": "Кожному вікну — свій сценарій",
    "category": "combat",
    "module": "Macro Studio",
    "seconds": 21,
    "date": "2026-09-13",
    "description": "Обери конкретного персонажа для дій макросу.",
    "status": "ready",
    "icon": "layers"
  },
  {
    "id": "xX83JV7Ke2E",
    "originalTitle": "Ціни з сумки  (Сyber.pw Асистент)",
    "title": "Що насправді лежить у сумці?",
    "category": "craft",
    "module": "Розумний інвентар",
    "seconds": 33,
    "date": "2026-09-13",
    "description": "Подивись ціни предметів із власного інвентаря.",
    "status": "ready",
    "icon": "bag"
  },
  {
    "id": "TLrNW3Kl4ug",
    "originalTitle": "безкоштовний свап  (Сyber.pw Асистент)",
    "title": "Зміни комплект гарячою клавішею",
    "category": "combat",
    "module": "AutoSwap",
    "seconds": 30,
    "date": "2026-09-13",
    "description": "Пресети A / B / C замість пошуку спорядження в бою.",
    "status": "ready",
    "icon": "swap"
  },
  {
    "id": "Vgui0B1ZjaI",
    "originalTitle": "resource map  (Сyber.pw Асистент)",
    "title": "Знайди потрібний ресурс",
    "category": "world",
    "module": "Карта ресурсів",
    "seconds": 33,
    "date": "2026-09-13",
    "description": "Обери точку та передай її координати в гру.",
    "status": "ready",
    "icon": "leaf"
  },
  {
    "id": "E5mF26HEH9I",
    "originalTitle": "macro market  (Сyber.pw Асистент)",
    "title": "Не збирай той самий макрос з нуля",
    "category": "combat",
    "module": "Macro Market",
    "seconds": 41,
    "date": "2026-09-13",
    "description": "Переглядай і встановлюй сценарії спільноти.",
    "status": "ready",
    "icon": "grid"
  },
  {
    "id": "vZHFQfM09hM",
    "originalTitle": "macro builder (Cyber.pw Асистент)",
    "title": "Збери власний сценарій",
    "category": "combat",
    "module": "Конструктор макросів",
    "seconds": 30,
    "date": "2026-09-13",
    "description": "Навички, клавіші та паузи в одній послідовності.",
    "status": "ready",
    "icon": "bolt"
  },
  {
    "id": "4H_kyExGpb8",
    "originalTitle": "world bosses  (Сyber.pw Асистент)",
    "title": "Боси: де, коли і як долетіти",
    "category": "world",
    "module": "Світові боси",
    "seconds": 30,
    "date": "2026-09-13",
    "description": "Час, місце і координати поруч із грою.",
    "status": "ready",
    "icon": "target"
  },
  {
    "id": "2fBhJOyitq0",
    "originalTitle": "знайди гайд  (Сyber.pw Асистент)",
    "title": "Той самий гайд, який ти загубив",
    "category": "world",
    "module": "Пошук гайдів",
    "seconds": 37,
    "date": "2026-09-13",
    "description": "Знайди матеріал у підготовленій базі форуму.",
    "status": "ready",
    "icon": "book"
  },
  {
    "id": "rQ6GyDR-7XY",
    "originalTitle": "Питання та відповіді (Cyber.pw Асистент)",
    "title": "Коли вікторина застала зненацька",
    "category": "world",
    "module": "Вікторини",
    "seconds": 19,
    "date": "2026-09-13",
    "description": "Пошук запитань і відповідей без окремих таблиць.",
    "status": "ready",
    "icon": "help"
  },
  {
    "id": "IUOVBiwj7dM",
    "originalTitle": "community  (Сyber.pw Асистент)",
    "title": "Спільнота прямо в Assistant",
    "category": "community",
    "module": "Спільний чат",
    "seconds": 30,
    "date": "2026-09-13",
    "description": "Знайомся з іншими користувачами помічника.",
    "status": "ready",
    "icon": "chat"
  },
  {
    "id": "lMI_1KTlcVw",
    "originalTitle": "simple profile  (Сyber.pw Асистент)",
    "title": "Профіль твого персонажа",
    "category": "community",
    "module": "Особистий профіль",
    "seconds": 26,
    "date": "2026-09-13",
    "description": "Подивись, як виглядає профіль усередині програми.",
    "status": "ready",
    "icon": "user"
  },
  {
    "id": "fsQjRM3SVNY",
    "originalTitle": "Симулятор скринь Сyber.pw Асистент",
    "title": "Перевір удачу без ігрових витрат",
    "category": "world",
    "module": "Симулятор скринь",
    "seconds": 16,
    "date": "2026-09-13",
    "description": "Симуляція — не прогноз наступного дропу в грі.",
    "status": "ready",
    "icon": "box"
  },
  {
    "id": "Y9d4Ecm-l-s",
    "originalTitle": "Огляд функцій Cyber,pw Асистент",
    "title": "Що вміє твій Assistant",
    "category": "all",
    "module": "Короткий огляд",
    "seconds": 41,
    "date": "2026-09-13",
    "description": "Від титулів до предметів і бойових інструментів.",
    "status": "ready",
    "icon": "fox"
  },
  {
    "id": "RGNwdQIsSUM",
    "originalTitle": "Hotfix 2 0 68 Cyber.pw Асистент",
    "title": "Оновлення інвентаря та стабільності",
    "category": "all",
    "module": "Hotfix 2.0.68",
    "seconds": 20,
    "date": "2026-09-13",
    "description": "Відео про попередній hotfix; поточний перевірений реліз — 2.0.70.",
    "status": "ready",
    "icon": "wrench"
  },
  {
    "id": "rGachlmtUWY",
    "originalTitle": "Авто пошук паті(Cyber.pw Асистент)",
    "title": "Пошук паті: напрямок розвитку",
    "category": "preview",
    "module": "Анонс / експеримент",
    "seconds": 24,
    "date": "2026-09-13",
    "description": "Не продаємо як готову функцію. Подивись авторський анонс.",
    "status": "preview",
    "icon": "users"
  },
  {
    "id": "-KziPcnPI70",
    "originalTitle": "Відьмача дошка оголошень (Cyber.pw Асистент)",
    "title": "Дошка оголошень: перший погляд",
    "category": "preview",
    "module": "Анонс / експеримент",
    "seconds": 21,
    "date": "2026-09-13",
    "description": "Попередня демонстрація, а не гарантія доступного сервісу.",
    "status": "preview",
    "icon": "board"
  },
  {
    "id": "UO0VZG2xbyY",
    "originalTitle": "Лялька з гри (Cyber.pw Асистент)",
    "title": "Лялька персонажа: прототип",
    "category": "preview",
    "module": "Coming Soon",
    "seconds": 19,
    "date": "2026-09-13",
    "description": "Повний розрахунок характеристик і онлайн-обмін ще не готові.",
    "status": "preview",
    "icon": "armor"
  }
];
